---
title: "Langton"
output: word_document
date: "2025-01-21"
---

# Setup

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(data.table)
library(here)
```

```{r getData}
#| eval: FALSE
# The originally generated data consist of nrow(ants) ticks on a 
#  grid that is 161 x 161. The patches data are sorted by (x,y), from
#  upper left to lower right, working across the rows. The ticks are 0-based
#  and in the original the grid is [-80,80] x [-80,80], with the upper left
#  corner being (-80,80).
#
# These were generated by NetLogo, and then the files were edited to remove
#  some unwanted characters.
#
# All patches not listed in Patches.txt are "white"; only "black" patches
#  are listed. 

fread(file = here("Data/Ants.txt"),
      col.names = c("Time", "X", "Y")) ->
  ants_df                                   # 12005 ticks
save(ants_df,
     file = here("Data/Ants.RData"))

fread(file = here("Data/Patches.txt"),
      col.names = c("Time", "X", "Y", "Col")) ->
  patches_df                                # 5,404,453 colored patches out of
                                            #  311,181,605 total patches.
patches_df[, -4] ->                         # Column 4 has only 1 unique value.
  patches_df
save(patches_df,
     file = here("Data/Patches.RData"))

```

```{r loadData}
load(here("Data/Patches.RData"))
load(here("Data/Ants.RData"))
```

```{r createDF}
# Make a data frame with tick, ant_x, ant_y, and the grid of pcolor. This
#  will be quite large, and so will slow things down unless (a) you work
#  in package::data.table format, (b) you use multiple cores (e.g., parallel
#  processing) and/or (c) are clever about management. Also, note that
#  a lot of the field was not used:
range(patches_df$X)                         # [1] -33  23
range(patches_df$Y)                         # [1] -29  57
# Hence, one does NOT need a gridsize of 161 x 161, but rather a grid of
#  [-35,25] x [-30,60] (where I put in some buffer so we can draw nicer
#  looking graphs). This is 61 * 91, which is only about a fifth of the
#  original grid. Still, after 12005 ticks, this will be almost 67 million
#  rows in long data format.

```

```{r plots}
plot(ants_df$X,
     ylim = c(-35,60),
     type = 'l',
     xlab = "Time",
     ylab = "X")
lines(ants_df$Y,
     col = "blue")

```

# Changepoints

First, find the classical changepoints with mean and variance
```{r}

```


Now, let's find the changepoints via windowed entropy or something like that.
```{r}

```

# Early Warning Signal





